spring:
  web:
  # 静态资源处理
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          # 缓存最大时间
          max-age: 3600
      chain:
        # 资源链启动缓存 默认启动
        cache: true
        # 启动资源链 默认禁用
        enabled: true
        # 启动压缩资源（gzip brotli）解析， 默认禁用
        compressed: true
        # 启用h5应用缓存 默认禁用
        html-application-cache: true
      add-mappings: true

  thymeleaf:
    # 不可缓存
    cache: false
  # rabbitmq配置
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port:
      5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次处理一条消息，处理完再处理下一条消息
        prefetch: 1
        #启动时是否默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      #消息被拒绝重试配置
      retry:
        #发表重试
        enabled: true
        #重试时间默认1000ms
        initial-interval: 1000ms
        #重试最大次数默认3次
        max-attempts: 3
        #重试最大间隔时间默认10000ms
        max-interval: 10000ms
        #重试最大间隔倍数，2的时候就是第一次10s 第二次20s 第三次40s
        multiplier: 1
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=UTC&useUnicode=ture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      # 连接池名字
      pool-name: Datapool
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲超时时间，默认600000（10min)
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接超时时间，默认30000（30s）
      connection-timeout: 30000
      # 测试连接是否可用语句
      connection-test-query: SELECT 1

  # redis设置
  redis:
    host: 47.99.171.23
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

mybatis-plus:
  # 配置mapper.xml映射文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类别名(默认别名是类名）
  type-aliases-package: com.pang.seckill.pojo

# mybatis sql 打印(方法接口所在的包，不是mapper映射文件的包）
logging:
  level:
    com.pang.seckill.mapper: debug
server:
  port: 8989
